# Generated by Django 5.2.1 on 2025-05-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0003_alter_governmentagency_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='ComplaintResponse',
        ),
    ]
