# Generated by Django 5.2.1 on 2025-05-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0004_rename_response_complaintresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
