# Generated by Django 5.2.1 on 2025-05-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0005_complaintresponse_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintresponse',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='managementsystem.governmentagency'),
        ),
        migrations.AddField(
            model_name='complaintresponse',
            name='is_agency_response',
            field=models.BooleanField(default=False),
        ),
    ]
