# Generated by Django 5.2.1 on 2025-05-17 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0006_complaintresponse_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintresponse',
            name='assigned_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaint_responses', to='managementsystem.governmentagency'),
        ),
        migrations.AddField(
            model_name='complaintresponse',
            name='complaint_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_responses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaintresponse',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_responses', to='managementsystem.governmentagency'),
        ),
        migrations.AlterField(
            model_name='complaintresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
